// Script pour comparer le PDF avec la base de données actuelle
import { vocabularyData } from './data/vocabulary';

// Mots extraits du PDF (715 mots)
const pdfWords = [
  // Page 1-3
  { japanese: "会う", hiragana: "あう", english: "to meet" },
  { japanese: "青", hiragana: "あお", english: "blue" },
  { japanese: "青い", hiragana: "あおい", english: "blue" },
  { japanese: "赤", hiragana: "あか", english: "red" },
  { japanese: "赤い", hiragana: "あかい", english: "red" },
  { japanese: "明るい", hiragana: "あかるい", english: "bright" },
  { japanese: "秋", hiragana: "あき", english: "autumn" },
  { japanese: "開く", hiragana: "あく", english: "to open, to become open" },
  { japanese: "開ける", hiragana: "あける", english: "to open" },
  { japanese: "上げる", hiragana: "あげる", english: "to give" },
  { japanese: "朝", hiragana: "あさ", english: "morning" },
  { japanese: "朝御飯", hiragana: "あさごはん", english: "breakfast" },
  { japanese: "", hiragana: "あさって", english: "day after tomorrow" },
  { japanese: "足", hiragana: "あし", english: "foot, leg" },
  { japanese: "明日", hiragana: "あした", english: "tomorrow" },
  { japanese: "", hiragana: "あそこ", english: "over there" },
  { japanese: "遊ぶ", hiragana: "あそぶ", english: "to play, to make a visit" },
  { japanese: "暖かい", hiragana: "あたたかい", english: "warm" },
  { japanese: "頭", hiragana: "あたま", english: "head" },
  { japanese: "新しい", hiragana: "あたらしい", english: "new" },
  { japanese: "", hiragana: "あちら", english: "there" },
  { japanese: "暑い", hiragana: "あつい", english: "hot" },
  { japanese: "熱い", hiragana: "あつい", english: "hot to the touch" },
  { japanese: "厚い", hiragana: "あつい", english: "kind, deep, thick" },
  { japanese: "", hiragana: "あっち", english: "over there" },
  { japanese: "後", hiragana: "あと", english: "afterwards" },
  { japanese: "", hiragana: "あなた", english: "you" },
  { japanese: "兄", hiragana: "あに", english: "(humble) older brother" },
  { japanese: "姉", hiragana: "あね", english: "(humble) older sister" },
  { japanese: "", hiragana: "あの", english: "that over there" },
  { japanese: "", hiragana: "あの", english: "um..." },
  { japanese: "アパート", hiragana: "あぱーと", english: "apartment" },
  { japanese: "", hiragana: "あびる", english: "to bathe, to shower" },
  { japanese: "危ない", hiragana: "あぶない", english: "dangerous" },
  { japanese: "甘い", hiragana: "あまい", english: "sweet" },
  { japanese: "", hiragana: "あまり", english: "not very" },
  { japanese: "雨", hiragana: "あめ", english: "rain" },
  { japanese: "飴", hiragana: "あめ", english: "candy" },
  { japanese: "洗う", hiragana: "あらう", english: "to wash" },
  { japanese: "", hiragana: "ある", english: "to be, to have (used for inanimate objects)" },
  { japanese: "歩く", hiragana: "あるく", english: "to walk" },
  { japanese: "", hiragana: "あれ", english: "that" },
  { japanese: "", hiragana: "いい/よい", english: "good" },
  { japanese: "", hiragana: "いいえ", english: "no" },
  { japanese: "言う", hiragana: "いう", english: "to say" },
  { japanese: "家", hiragana: "いえ", english: "house" },
  { japanese: "", hiragana: "いかが", english: "how" },
  { japanese: "行く", hiragana: "いく", english: "to go" },
  { japanese: "", hiragana: "いくつ", english: "how many?, how old?" },
  { japanese: "", hiragana: "いくら", english: "how much?" },
  { japanese: "池", hiragana: "いけ", english: "pond" },
  { japanese: "医者", hiragana: "いしゃ", english: "medical doctor" },
  { japanese: "", hiragana: "いす", english: "chair" },
  { japanese: "忙しい", hiragana: "いそがしい", english: "busy, irritated" },
  { japanese: "痛い", hiragana: "いたい", english: "painful" },
  { japanese: "一", hiragana: "いち", english: "one" },
  { japanese: "一日", hiragana: "いちにち", english: "first of the month" },
  { japanese: "", hiragana: "いちばん", english: "best, first" },
  { japanese: "", hiragana: "いつ", english: "when" },
  { japanese: "五日", hiragana: "いつか", english: "five days, fifth day" },
  { japanese: "一緒", hiragana: "いっしょ", english: "together" },
  { japanese: "五つ", hiragana: "いつつ", english: "five" },
  { japanese: "", hiragana: "いつも", english: "always" },
  { japanese: "犬", hiragana: "いぬ", english: "dog" },
  { japanese: "今", hiragana: "いま", english: "now" },
  { japanese: "意味", hiragana: "いみ", english: "meaning" },
  { japanese: "妹", hiragana: "いもうと", english: "(humble) younger sister" },
  { japanese: "嫌", hiragana: "いや", english: "unpleasant" },
  { japanese: "入口", hiragana: "いりぐち", english: "entrance" },
  { japanese: "居る", hiragana: "いる", english: "to be, to have (used for people and animals)" },
  { japanese: "要る", hiragana: "いる", english: "to need" },
  { japanese: "入れる", hiragana: "いれる", english: "to put in" },
  { japanese: "色", hiragana: "いろ", english: "colour" },
  { japanese: "", hiragana: "いろいろ", english: "various" },
  { japanese: "上", hiragana: "うえ", english: "on top of" },
  { japanese: "後ろ", hiragana: "うしろ", english: "behind" },
  { japanese: "薄い", hiragana: "うすい", english: "thin, weak" },
  { japanese: "歌", hiragana: "うた", english: "song" },
  { japanese: "歌う", hiragana: "うたう", english: "to sing" },
  { japanese: "生まれる", hiragana: "うまれる", english: "to be born" },
  { japanese: "海", hiragana: "うみ", english: "sea" },
  { japanese: "売る", hiragana: "うる", english: "to sell" },
  { japanese: "煩い", hiragana: "うるさい", english: "noisy, annoying" },
  { japanese: "上着", hiragana: "うわぎ", english: "jacket" },
  { japanese: "絵", hiragana: "え", english: "picture" },
  { japanese: "映画", hiragana: "えいが", english: "movie" },
  { japanese: "映画館", hiragana: "えいがかん", english: "cinema" },
  { japanese: "英語", hiragana: "えいご", english: "English language" },
  { japanese: "", hiragana: "ええ", english: "yes" },
  { japanese: "駅", hiragana: "えき", english: "station" },
  { japanese: "", hiragana: "エレベーター", english: "elevator" },
  { japanese: "鉛筆", hiragana: "えんぴつ", english: "pencil" },
  { japanese: "", hiragana: "おいしい", english: "delicious" },
  { japanese: "多い", hiragana: "おおい", english: "many" },
  { japanese: "大きい", hiragana: "おおきい", english: "big" },
  { japanese: "大きな", hiragana: "おおきな", english: "big" },
  { japanese: "大勢", hiragana: "おおぜい", english: "great number of people" },
  { japanese: "お母さん", hiragana: "おかあさん", english: "(honorable) mother" },
  { japanese: "お菓子", hiragana: "おかし", english: "sweets, candy" },
  { japanese: "お金", hiragana: "おかね", english: "money" },
  { japanese: "起きる", hiragana: "おきる", english: "to get up" },
  { japanese: "置く", hiragana: "おく", english: "to put" },
  { japanese: "奥さん", hiragana: "おくさん", english: "(honorable) wife" },
  { japanese: "お酒", hiragana: "おさけ", english: "alcohol, rice wine" },
  { japanese: "お皿", hiragana: "おさら", english: "plate, dish" },
  { japanese: "伯父/叔父", hiragana: "おじいさん", english: "grandfather, male senior citizen" },
  { japanese: "教える", hiragana: "おしえる", english: "to teach, to tell" },
  { japanese: "伯父/叔父", hiragana: "おじさん", english: "uncle, middle aged gentleman" },
  { japanese: "押す", hiragana: "おす", english: "to push, to stamp something" },
  { japanese: "遅い", hiragana: "おそい", english: "late, slow" },
  { japanese: "お茶", hiragana: "おちゃ", english: "green tea" },
  { japanese: "お手洗い", hiragana: "おてあらい", english: "bathroom" },
  { japanese: "お父さん", hiragana: "おとうさん", english: "(honorable) father" },
  { japanese: "弟", hiragana: "おとうと", english: "younger brother" },
  { japanese: "男", hiragana: "おとこ", english: "Man" },
  { japanese: "男の子", hiragana: "おとこのこ", english: "Boy" },
  { japanese: "一昨日", hiragana: "おととい", english: "day before yesterday" },
  { japanese: "一昨年", hiragana: "おととし", english: "year before last" },
  { japanese: "大人", hiragana: "おとな", english: "Adult" },
  { japanese: "", hiragana: "おなか", english: "stomach" },
  { japanese: "同じ", hiragana: "おなじ", english: "same" },
  { japanese: "お兄さん", hiragana: "おにいさん", english: "(honorable) older brother" },
  { japanese: "お姉さん", hiragana: "おねえさん", english: "(honorable) older sister" },
  { japanese: "", hiragana: "おばあさん", english: "grandmother, female senior-citizen" },
  { japanese: "伯母さん/叔母さん", hiragana: "おばさん", english: "Aunt" },
  { japanese: "お風呂", hiragana: "おふろ", english: "Bath" },
  { japanese: "お弁当", hiragana: "おべんとう", english: "boxed lunch" },
  { japanese: "覚える", hiragana: "おぼえる", english: "to remember" },
  { japanese: "", hiragana: "おまわりさん", english: "friendly term for policeman" },
  { japanese: "重い", hiragana: "おもい", english: "Heavy" },
  { japanese: "", hiragana: "おもしろい", english: "Interesting" },
  { japanese: "泳ぐ", hiragana: "およぐ", english: "to swim" },
  { japanese: "降りる", hiragana: "おりる", english: "to get off, to descend" },
  { japanese: "終る", hiragana: "おわる", english: "to finish" },
  { japanese: "音楽", hiragana: "おんがく", english: "Music" },
  { japanese: "女", hiragana: "おんな", english: "Woman" },
  { japanese: "女の子", hiragana: "おんなのこ", english: "Girl" },
  { japanese: "外国", hiragana: "がいこく", english: "foreign country" },
  { japanese: "外国人", hiragana: "がいこくじん", english: "Foreigner" },
  { japanese: "会社", hiragana: "かいしゃ", english: "Company" },
  { japanese: "階段", hiragana: "かいだん", english: "Stairs" },
  { japanese: "買い物", hiragana: "かいもの", english: "Shopping" },
  { japanese: "買う", hiragana: "かう", english: "to buy" },
  { japanese: "返す", hiragana: "かえす", english: "to return something" },
  { japanese: "帰る", hiragana: "かえる", english: "to go back" },
  { japanese: "", hiragana: "かかる", english: "to take time or money" },
  { japanese: "", hiragana: "かぎ", english: "Key" },
  { japanese: "書く", hiragana: "かく", english: "to write" },
  { japanese: "学生", hiragana: "がくせい", english: "Student" },
  { japanese: "", hiragana: "かける", english: "to call by phone" },
  { japanese: "傘", hiragana: "かさ", english: "Umbrella" },
  { japanese: "貸す", hiragana: "かす", english: "to lend" },
  { japanese: "風", hiragana: "かぜ", english: "Wind" },
  { japanese: "風邪", hiragana: "かぜ", english: "a cold" },
  { japanese: "家族", hiragana: "かぞく", english: "Family" },
  { japanese: "方", hiragana: "かた", english: "person, way of doing" },
  { japanese: "学校", hiragana: "がっこう", english: "School" },
  { japanese: "", hiragana: "カップ", english: "Cup" },
  { japanese: "家庭", hiragana: "かてい", english: "Household" },
  { japanese: "角", hiragana: "かど", english: "a corner" },
  { japanese: "", hiragana: "かばん", english: "bag, basket" },
  { japanese: "花瓶", hiragana: "かびん", english: "a vase" },
  { japanese: "紙", hiragana: "かみ", english: "paper" },
  { japanese: "", hiragana: "カメラ", english: "camera" },
  { japanese: "火曜日", hiragana: "かようび", english: "Tuesday" },
  { japanese: "体", hiragana: "からだ", english: "body" },
  { japanese: "借りる", hiragana: "かりる", english: "to borrow" },
  { japanese: "軽い", hiragana: "かるい", english: "light" },
  { japanese: "川", hiragana: "かわ", english: "river" },
  { japanese: "可愛い", hiragana: "かわいい", english: "cute" },
  { japanese: "", hiragana: "かん", english: "can, tin" },
  { japanese: "漢字", hiragana: "かんじ", english: "Chinese characters" },
  { japanese: "木", hiragana: "き", english: "tree" },
  { japanese: "黄色", hiragana: "きいろ", english: "yellow" },
  { japanese: "黄色い", hiragana: "きいろい", english: "yellow" },
  { japanese: "消える", hiragana: "きえる", english: "to disappear" },
  { japanese: "聞く", hiragana: "きく", english: "to listen, to ask" },
  { japanese: "北", hiragana: "きた", english: "north" },
  { japanese: "汚い", hiragana: "きたない", english: "dirty" },
  { japanese: "", hiragana: "きっと", english: "certainly" },
  { japanese: "切手", hiragana: "きって", english: "postage stamp" },
  { japanese: "喫茶店", hiragana: "きっさてん", english: "coffee shop" },
  { japanese: "昨日", hiragana: "きのう", english: "yesterday" },
  { japanese: "気分", hiragana: "きぶん", english: "feeling" },
  { japanese: "君", hiragana: "きみ", english: "you (very casual)" },
  { japanese: "決める", hiragana: "きめる", english: "to decide" },
  { japanese: "着物", hiragana: "きもの", english: "kimono" },
  { japanese: "客", hiragana: "きゃく", english: "guest, customer" },
  { japanese: "九", hiragana: "きゅう", english: "nine" },
  { japanese: "牛乳", hiragana: "ぎゅうにく", english: "milk" },
  { japanese: "今日", hiragana: "きょう", english: "today" },
  { japanese: "教室", hiragana: "きょうしつ", english: "classroom" },
  { japanese: "兄弟", hiragana: "きょうだい", english: "brothers and sisters" },
  { japanese: "去年", hiragana: "きょねん", english: "last year" },
  { japanese: "嫌い", hiragana: "きらい", english: "hate" },
  { japanese: "切る", hiragana: "きる", english: "to cut" },
  { japanese: "着る", hiragana: "きる", english: "to wear" },
  { japanese: "綺麗", hiragana: "きれい", english: "pretty, clean" },
  { japanese: "銀行", hiragana: "ぎんこう", english: "bank" },
  { japanese: "金曜日", hiragana: "きんようび", english: "Friday" },
  { japanese: "薬", hiragana: "くすり", english: "medicine" },
  { japanese: "下さい", hiragana: "ください", english: "please" },
  { japanese: "果物", hiragana: "くだもの", english: "fruit" },
  { japanese: "口", hiragana: "くち", english: "mouth" },
  { japanese: "靴", hiragana: "くつ", english: "shoes" },
  { japanese: "靴下", hiragana: "くつした", english: "socks" },
  { japanese: "国", hiragana: "くに", english: "country" },
  { japanese: "曇り", hiragana: "くもり", english: "cloudy weather" },
  { japanese: "曇る", hiragana: "くもる", english: "to become cloudy" },
  { japanese: "暗い", hiragana: "くらい", english: "dark" },
  { japanese: "クラス", hiragana: "くらす", english: "class" },
  { japanese: "来る", hiragana: "くる", english: "to come" },
  { japanese: "車", hiragana: "くるま", english: "car" },
  { japanese: "黒い", hiragana: "くろい", english: "black" },
  { japanese: "警官", hiragana: "けいかん", english: "policeman" },
  { japanese: "今朝", hiragana: "けさ", english: "this morning" },
  { japanese: "消す", hiragana: "けす", english: "to erase, to turn off" },
  { japanese: "結婚", hiragana: "けっこん", english: "marriage" },
  { japanese: "月曜日", hiragana: "げつようび", english: "Monday" },
  { japanese: "元気", hiragana: "げんき", english: "healthy" },
  { japanese: "玄関", hiragana: "げんかん", english: "entrance" },
  { japanese: "", hiragana: "こ", english: "this" },
  { japanese: "公園", hiragana: "こうえん", english: "park" },
  { japanese: "交差点", hiragana: "こうさてん", english: "intersection" },
  { japanese: "高校", hiragana: "こうこう", english: "high school" },
  { japanese: "紅茶", hiragana: "こうちゃ", english: "black tea" },
  { japanese: "声", hiragana: "こえ", english: "voice" },
  { japanese: "ここ", hiragana: "ここ", english: "here" },
  { japanese: "九日", hiragana: "ここのか", english: "nine days, ninth day" },
  { japanese: "九つ", hiragana: "ここのつ", english: "nine" },
  { japanese: "午後", hiragana: "ごご", english: "afternoon" },
  { japanese: "午前", hiragana: "ごぜん", english: "morning (am)" },
  { japanese: "答える", hiragana: "こたえる", english: "to answer" },
  { japanese: "", hiragana: "こちら", english: "this way" },
  { japanese: "子供", hiragana: "こども", english: "child" },
  { japanese: "今年", hiragana: "ことし", english: "this year" },
  { japanese: "言葉", hiragana: "ことば", english: "word" },
  { japanese: "今度", hiragana: "こんど", english: "this time" },
  { japanese: "今晩", hiragana: "こんばん", english: "tonight" },
  { japanese: "魚", hiragana: "さかな", english: "fish" },
  { japanese: "先", hiragana: "さき", english: "earlier, previous" },
  { japanese: "作文", hiragana: "さくぶん", english: "composition" },
  { japanese: "差す", hiragana: "さす", english: "to put up an umbrella" },
  { japanese: "雑誌", hiragana: "ざっし", english: "magazine" },
  { japanese: "砂糖", hiragana: "さとう", english: "sugar" },
  { japanese: "寂しい", hiragana: "さびしい", english: "lonely" },
  { japanese: "侍", hiragana: "さむらい", english: "samurai" },
  { japanese: "寒い", hiragana: "さむい", english: "cold" },
  { japanese: "皿", hiragana: "さら", english: "plate" },
  { japanese: "三", hiragana: "さん", english: "three" },
  { japanese: "散歩", hiragana: "さんぽ", english: "walk, stroll" },
  { japanese: "塩", hiragana: "しお", english: "salt" },
  { japanese: "時間", hiragana: "じかん", english: "time" },
  { japanese: "仕事", hiragana: "しごと", english: "work" },
  { japanese: "辞書", hiragana: "じしょ", english: "dictionary" },
  { japanese: "静か", hiragana: "しずか", english: "quiet" },
  { japanese: "下", hiragana: "した", english: "below" },
  { japanese: "親しい", hiragana: "したしい", english: "intimate" },
  { japanese: "七", hiragana: "しち", english: "seven" },
  { japanese: "質問", hiragana: "しつもん", english: "question" },
  { japanese: "自転車", hiragana: "じてんしゃ", english: "bicycle" },
  { japanese: "死ぬ", hiragana: "しぬ", english: "to die" },
  { japanese: "芝生", hiragana: "しばふ", english: "lawn" },
  { japanese: "閉まる", hiragana: "しまる", english: "to be closed" },
  { japanese: "閉める", hiragana: "しめる", english: "to close" },
  { japanese: "写真", hiragana: "しゃしん", english: "photograph" },
  { japanese: "シャツ", hiragana: "しゃつ", english: "shirt" },
  { japanese: "シャワー", hiragana: "しゃわー", english: "shower" },
  { japanese: "週間", hiragana: "しゅうかん", english: "week" },
  { japanese: "宿題", hiragana: "しゅくだい", english: "homework" },
  { japanese: "上手", hiragana: "じょうず", english: "skillful" },
  { japanese: "醤油", hiragana: "しょうゆ", english: "soy sauce" },
  { japanese: "食堂", hiragana: "しょくどう", english: "cafeteria" },
  { japanese: "知る", hiragana: "しる", english: "to get to know" },
  { japanese: "白い", hiragana: "しろい", english: "white" },
  { japanese: "新聞", hiragana: "しんぶん", english: "newspaper" },
  { japanese: "水曜日", hiragana: "すいようび", english: "Wednesday" },
  { japanese: "好き", hiragana: "すき", english: "to like" },
  { japanese: "少し", hiragana: "すこし", english: "a little" },
  { japanese: "涼しい", hiragana: "すずしい", english: "cool" },
  { japanese: "ストーブ", hiragana: "すとーぶ", english: "heater" },
  { japanese: "住む", hiragana: "すむ", english: "to live" },
  { japanese: "相撲", hiragana: "すもう", english: "sumo wrestling" },
  { japanese: "する", hiragana: "する", english: "to do" },
  { japanese: "座る", hiragana: "すわる", english: "to sit" },
  { japanese: "背", hiragana: "せ", english: "height, stature" },
  { japanese: "生活", hiragana: "せいかつ", english: "life" },
  { japanese: "生徒", hiragana: "せいと", english: "student" },
  { japanese: "背中", hiragana: "せなか", english: "back" },
  { japanese: "狭い", hiragana: "せまい", english: "narrow" },
  { japanese: "洗濯", hiragana: "せんたく", english: "washing" },
  { japanese: "先生", hiragana: "せんせい", english: "teacher" },
  { japanese: "先週", hiragana: "せんしゅう", english: "last week" },
  { japanese: "そうじ", hiragana: "そうじ", english: "cleaning" },
  { japanese: "外", hiragana: "そと", english: "outside" },
  { japanese: "その", hiragana: "その", english: "that" },
  { japanese: "空", hiragana: "そら", english: "sky" },
  { japanese: "それ", hiragana: "それ", english: "that" },
  { japanese: "大学", hiragana: "だいがく", english: "university" },
  { japanese: "大丈夫", hiragana: "だいじょうぶ", english: "all right" },
  { japanese: "台所", hiragana: "だいどころ", english: "kitchen" },
  { japanese: "大好き", hiragana: "だいすき", english: "to like very much" },
  { japanese: "高い", hiragana: "たかい", english: "high, expensive" },
  { japanese: "たくさん", hiragana: "たくさん", english: "many, a lot" },
  { japanese: "タクシー", hiragana: "たくしー", english: "taxi" },
  { japanese: "竹", hiragana: "たけ", english: "bamboo" },
  { japanese: "出す", hiragana: "だす", english: "to put out" },
  { japanese: "立つ", hiragana: "たつ", english: "to stand" },
  { japanese: "建物", hiragana: "たてもの", english: "building" },
  { japanese: "楽しい", hiragana: "たのしい", english: "fun" },
  { japanese: "頼む", hiragana: "たのむ", english: "to ask a favour" },
  { japanese: "煙草", hiragana: "たばこ", english: "cigarette" },
  { japanese: "食べ物", hiragana: "たべもの", english: "food" },
  { japanese: "卵", hiragana: "たまご", english: "egg" },
  { japanese: "誰", hiragana: "だれ", english: "who" },
  { japanese: "誕生日", hiragana: "たんじょうび", english: "birthday" },
  { japanese: "小さい", hiragana: "ちいさい", english: "small" },
  { japanese: "小さな", hiragana: "ちいさな", english: "small" },
  { japanese: "近い", hiragana: "ちかい", english: "close" },
  { japanese: "地下鉄", hiragana: "ちかてつ", english: "underground" },
  { japanese: "違う", hiragana: "ちがう", english: "to differ" },
  { japanese: "地図", hiragana: "ちず", english: "map" },
  { japanese: "茶色", hiragana: "ちゃいろ", english: "brown" },
  { japanese: "茶色い", hiragana: "ちゃいろい", english: "brown" },
  { japanese: "茶碗", hiragana: "ちゃわん", english: "rice bowl" },
  { japanese: "中学校", hiragana: "ちゅうがっこう", english: "junior high school" },
  { japanese: "注意", hiragana: "ちゅうい", english: "caution" },
  { japanese: "丁度", hiragana: "ちょうど", english: "exactly" },
  { japanese: "使う", hiragana: "つかう", english: "to use" },
  { japanese: "疲れる", hiragana: "つかれる", english: "to get tired" },
  { japanese: "付く", hiragana: "つく", english: "to arrive" },
  { japanese: "机", hiragana: "つくえ", english: "desk" },
  { japanese: "作る", hiragana: "つくる", english: "to make" },
  { japanese: "詰まらない", hiragana: "つまらない", english: "boring" },
  { japanese: "冷たい", hiragana: "つめたい", english: "cold to the touch" },
  { japanese: "強い", hiragana: "つよい", english: "strong" },
  { japanese: "釣り", hiragana: "つり", english: "fishing" },
  { japanese: "手", hiragana: "て", english: "hand" },
  { japanese: "テープ", hiragana: "てーぷ", english: "tape" },
  { japanese: "テーブル", hiragana: "てーぶる", english: "table" },
  { japanese: "手紙", hiragana: "てがみ", english: "letter" },
  { japanese: "出口", hiragana: "でぐち", english: "exit" },
  { japanese: "出来る", hiragana: "できる", english: "to be able to do" },
  { japanese: "デパート", hiragana: "でぱーと", english: "department store" },
  { japanese: "出る", hiragana: "でる", english: "to go out" },
  { japanese: "電気", hiragana: "でんき", english: "electricity" },
  { japanese: "電車", hiragana: "でんしゃ", english: "electric train" },
  { japanese: "電話", hiragana: "でんわ", english: "telephone" },
  { japanese: "戸", hiragana: "と", english: "door" },
  { japanese: "トイレ", hiragana: "といれ", english: "toilet" },
  { japanese: "十日", hiragana: "とおか", english: "ten days, tenth day" },
  { japanese: "遠い", hiragana: "とおい", english: "far" },
  { japanese: "十", hiragana: "とお", english: "ten" },
  { japanese: "通る", hiragana: "とおる", english: "to go through" },
  { japanese: "時計", hiragana: "とけい", english: "clock, watch" },
  { japanese: "所", hiragana: "ところ", english: "place" },
  { japanese: "図書館", hiragana: "としょかん", english: "library" },
  { japanese: "年", hiragana: "とし", english: "year" },
  { japanese: "となり", hiragana: "となり", english: "next door" },
  { japanese: "飛ぶ", hiragana: "とぶ", english: "to fly" },
  { japanese: "止まる", hiragana: "とまる", english: "to stop" },
  { japanese: "友達", hiragana: "ともだち", english: "friend" },
  { japanese: "土曜日", hiragana: "どようび", english: "Saturday" },
  { japanese: "鳥", hiragana: "とり", english: "bird" },
  { japanese: "撮る", hiragana: "とる", english: "to take a photograph" },
  { japanese: "取る", hiragana: "とる", english: "to take" },
  { japanese: "どれ", hiragana: "どれ", english: "which (of three or more)" },
  { japanese: "", hiragana: "ナイフ", english: "knife" },
  { japanese: "中", hiragana: "なか", english: "middle" },
  { japanese: "長い", hiragana: "ながい", english: "long" },
  { japanese: "鳴く", hiragana: "なく", english: "animal noise. to chirp, roar or croak etc." },
  { japanese: "無くす", hiragana: "なくす", english: "to lose something" },
  { japanese: "", hiragana: "なぜ", english: "why" },
  { japanese: "夏", hiragana: "なつ", english: "summer" },
  { japanese: "夏休み", hiragana: "なつやすみ", english: "summer holiday" },
  { japanese: "", hiragana: "など", english: "et cetera" },
  { japanese: "七つ", hiragana: "ななつ", english: "seven" },
  { japanese: "七日", hiragana: "なのか", english: "seven days, the seventh day" },
  { japanese: "名前", hiragana: "なまえ", english: "name" },
  { japanese: "習う", hiragana: "ならう", english: "to learn" },
  { japanese: "並ぶ", hiragana: "ならぶ", english: "to line up, to stand in a line" },
  { japanese: "並べる", hiragana: "ならべる", english: "to line up, to set up" },
  { japanese: "", hiragana: "なる", english: "to become" },
  { japanese: "何", hiragana: "なん/なに", english: "what" },
  { japanese: "二", hiragana: "に", english: "two" },
  { japanese: "賑やか", hiragana: "にぎやか", english: "bustling, busy" },
  { japanese: "肉", hiragana: "にく", english: "meat" },
  { japanese: "西", hiragana: "にし", english: "west" },
  { japanese: "日曜日", hiragana: "にちようび", english: "Sunday" },
  { japanese: "荷物", hiragana: "にもつ", english: "luggage" },
  { japanese: "", hiragana: "ニュース", english: "news" },
  { japanese: "庭", hiragana: "にわ", english: "garden" },
  { japanese: "脱ぐ", hiragana: "ぬぐ", english: "to take off clothes" },
  { japanese: "温い", hiragana: "ぬるい", english: "luke warm" },
  { japanese: "", hiragana: "ネクタイ", english: "tie, necktie" },
  { japanese: "猫", hiragana: "ねこ", english: "cat" },
  { japanese: "寝る", hiragana: "ねる", english: "to go to bed, to sleep" },
  { japanese: "", hiragana: "ノート", english: "notebook, exercise book" },
  { japanese: "登る", hiragana: "のぼる", english: "to climb" },
  { japanese: "飲み物", hiragana: "のみもの", english: "a drink" },
  { japanese: "飲む", hiragana: "のむ", english: "to drink" },
  { japanese: "乗る", hiragana: "のる", english: "to get on, to ride" },
  { japanese: "歯", hiragana: "は", english: "tooth" },
  { japanese: "", hiragana: "パーティー", english: "party" },
  { japanese: "", hiragana: "はい", english: "yes" },
  { japanese: "灰皿", hiragana: "はいざら", english: "ashtray" },
  { japanese: "入る", hiragana: "はいる", english: "to enter, to contain" },
  { japanese: "葉書", hiragana: "はがき", english: "postcard" },
  { japanese: "", hiragana: "はく", english: "to wear, to put on trousers" },
  { japanese: "箱", hiragana: "はこ", english: "box" },
  { japanese: "橋", hiragana: "はし", english: "bridge" },
  { japanese: "", hiragana: "はし", english: "chopsticks" },
  { japanese: "始まる", hiragana: "はじまる", english: "to begin" },
  { japanese: "初め/始め", hiragana: "はじめ", english: "beginning" },
  { japanese: "初めて", hiragana: "はじめて", english: "for the first time" },
  { japanese: "走る", hiragana: "はしる", english: "to run" },
  { japanese: "", hiragana: "バス", english: "bus" },
  { japanese: "", hiragana: "バター", english: "butter" },
  { japanese: "二十歳", hiragana: "はたち", english: "20 years old, 20th year" },
  { japanese: "働く", hiragana: "はたらく", english: "to work" },
  { japanese: "八", hiragana: "はち", english: "eight" },
  { japanese: "二十日", hiragana: "はつか", english: "twenty days, twentieth" },
  { japanese: "花", hiragana: "はな", english: "flower" },
  { japanese: "鼻", hiragana: "はな", english: "nose" },
  { japanese: "話", hiragana: "はなし", english: "talk, story" },
  { japanese: "話す", hiragana: "はなす", english: "to speak" },
  { japanese: "早い", hiragana: "はやい", english: "early" },
  { japanese: "速い", hiragana: "はやい", english: "quick" },
  { japanese: "春", hiragana: "はる", english: "spring" },
  { japanese: "貼る", hiragana: "はる", english: "to stick" },
  { japanese: "晴れ", hiragana: "はれ", english: "clear weather" },
  { japanese: "晴れる", hiragana: "はれる", english: "to be sunny" },
  { japanese: "半", hiragana: "はん", english: "half" },
  { japanese: "晩", hiragana: "ばん", english: "evening" },
  { japanese: "", hiragana: "パン", english: "bread" },
  { japanese: "", hiragana: "ハンカチ", english: "handkerchief" },
  { japanese: "番号", hiragana: "ばんごう", english: "number" },
  { japanese: "晩御飯", hiragana: "ばんごはん", english: "evening meal" },
  { japanese: "半分", hiragana: "はんぶん", english: "half minute" },
  { japanese: "東", hiragana: "ひがし", english: "east" },
  { japanese: "引く", hiragana: "ひく", english: "to pull" },
  { japanese: "弾く", hiragana: "ひく", english: "to play an instrument with strings, including piano" },
  { japanese: "低い", hiragana: "ひくい", english: "short, low" },
  { japanese: "飛行機", hiragana: "ひこうき", english: "aeroplane" },
  { japanese: "左", hiragana: "ひだり", english: "left hand side" },
  { japanese: "人", hiragana: "ひと", english: "person" },
  { japanese: "一つ", hiragana: "ひとつ", english: "one" },
  { japanese: "一月", hiragana: "ひとつき", english: "one month" },
  { japanese: "一人", hiragana: "ひとり", english: "one person" },
  { japanese: "暇", hiragana: "ひま", english: "free time" },
  { japanese: "百", hiragana: "ひゃく", english: "hundred" },
  { japanese: "病院", hiragana: "びょういん", english: "hospital" },
  { japanese: "病気", hiragana: "びょうき", english: "illness" },
  { japanese: "昼", hiragana: "ひる", english: "noon, daytime" },
  { japanese: "昼御飯", hiragana: "ひるごはん", english: "midday meal" },
  { japanese: "広い", hiragana: "ひろい", english: "spacious, wide" },
  { japanese: "", hiragana: "フィルム", english: "roll of film" },
  { japanese: "封筒", hiragana: "ふうとう", english: "envelope" },
  { japanese: "", hiragana: "プール", english: "swimming pool" },
  { japanese: "", hiragana: "フォーク", english: "fork" },
  { japanese: "吹く", hiragana: "ふく", english: "to blow" },
  { japanese: "服", hiragana: "ふく", english: "clothes" },
  { japanese: "二つ", hiragana: "ふたつ", english: "two" },
  { japanese: "豚肉", hiragana: "ぶたにく", english: "pork" },
  { japanese: "二人", hiragana: "ふたり", english: "two people" },
  { japanese: "二日", hiragana: "ふつか", english: "two days, second day of the month" },
  { japanese: "太い", hiragana: "ふとい", english: "fat" },
  { japanese: "冬", hiragana: "ふゆ", english: "winter" },
  { japanese: "降る", hiragana: "ふる", english: "to fall, e.g. rain or snow" },
  { japanese: "古い", hiragana: "ふるい", english: "old (not used for people)" },
  { japanese: "", hiragana: "ふろ", english: "bath" },
  { japanese: "文章", hiragana: "ぶんしょう", english: "sentence, text" },
  { japanese: "", hiragana: "ページ", english: "page" },
  { japanese: "下手", hiragana: "へた", english: "unskillful" },
  { japanese: "", hiragana: "ベッド", english: "bed" },
  { japanese: "", hiragana: "ペット", english: "pet" },
  { japanese: "部屋", hiragana: "へや", english: "room" },
  { japanese: "勉強", hiragana: "べんきょう", english: "study" },
  { japanese: "便利", hiragana: "べんり", english: "convenient" },
  { japanese: "帽子", hiragana: "ぼうし", english: "hat" },
  { japanese: "僕", hiragana: "ぼく", english: "I (used by boys and men)" },
  { japanese: "欲しい", hiragana: "ほしい", english: "to want something" },
  { japanese: "細い", hiragana: "ほそい", english: "thin" },
  { japanese: "", hiragana: "ボタン", english: "button" },
  { japanese: "", hiragana: "ポケット", english: "pocket" },
  { japanese: "本", hiragana: "ほん", english: "book" },
  { japanese: "本当", hiragana: "ほんとう", english: "truth" },
  { japanese: "本屋", hiragana: "ほんや", english: "bookshop" },
  { japanese: "毎朝", hiragana: "まいあさ", english: "every morning" },
  { japanese: "毎晩", hiragana: "まいばん", english: "every night" },
  { japanese: "毎日", hiragana: "まいにち", english: "every day" },
  { japanese: "前", hiragana: "まえ", english: "before" },
  { japanese: "曲がる", hiragana: "まがる", english: "to turn" },
  { japanese: "負ける", hiragana: "まける", english: "to lose" },
  { japanese: "孫", hiragana: "まご", english: "grandchild" },
  { japanese: "真面目", hiragana: "まじめ", english: "serious" },
  { japanese: "混ぜる", hiragana: "まぜる", english: "to mix" },
  { japanese: "待つ", hiragana: "まつ", english: "to wait" },
  { japanese: "真っ直ぐ", hiragana: "まっすぐ", english: "straight" },
  { japanese: "窓", hiragana: "まど", english: "window" },
  { japanese: "丸い", hiragana: "まるい", english: "round" },
  { japanese: "万", hiragana: "まん", english: "ten thousand" },
  { japanese: "万年筆", hiragana: "まんねんひつ", english: "fountain pen" },
  { japanese: "右", hiragana: "みぎ", english: "right hand side" },
  { japanese: "短い", hiragana: "みじかい", english: "short" },
  { japanese: "見せる", hiragana: "みせる", english: "to show" },
  { japanese: "店", hiragana: "みせ", english: "shop" },
  { japanese: "道", hiragana: "みち", english: "road" },
  { japanese: "三日", hiragana: "みっか", english: "three days, third day" },
  { japanese: "三つ", hiragana: "みっつ", english: "three" },
  { japanese: "緑", hiragana: "みどり", english: "green" },
  { japanese: "皆", hiragana: "みな", english: "everyone" },
  { japanese: "南", hiragana: "みなみ", english: "south" },
  { japanese: "耳", hiragana: "みみ", english: "ear" },
  { japanese: "見る", hiragana: "みる", english: "to see" },
  { japanese: "牛乳", hiragana: "ぎゅうにゅう", english: "milk" },
  { japanese: "向こう", hiragana: "むこう", english: "over there" },
  { japanese: "六日", hiragana: "むいか", english: "six days, sixth day" },
  { japanese: "難しい", hiragana: "むずかしい", english: "difficult" },
  { japanese: "六つ", hiragana: "むっつ", english: "six" },
  { japanese: "村", hiragana: "むら", english: "village" },
  { japanese: "迎える", hiragana: "むかえる", english: "to go and meet" },
  { japanese: "目", hiragana: "め", english: "eye" },
  { japanese: "眼鏡", hiragana: "めがね", english: "glasses" },
  { japanese: "木曜日", hiragana: "もくようび", english: "Thursday" },
  { japanese: "持つ", hiragana: "もつ", english: "to hold" },
  { japanese: "", hiragana: "もっと", english: "more" },
  { japanese: "物", hiragana: "もの", english: "thing" },
  { japanese: "門", hiragana: "もん", english: "gate" },
  { japanese: "問題", hiragana: "もんだい", english: "problem" },
  { japanese: "八百屋", hiragana: "やおや", english: "greengrocer" },
  { japanese: "野菜", hiragana: "やさい", english: "vegetable" },
  { japanese: "易しい", hiragana: "やさしい", english: "easy, simple" },
  { japanese: "安い", hiragana: "やすい", english: "cheap" },
  { japanese: "休み", hiragana: "やすみ", english: "rest, holiday" },
  { japanese: "休む", hiragana: "やすむ", english: "to rest" },
  { japanese: "八つ", hiragana: "やっつ", english: "eight" },
  { japanese: "山", hiragana: "やま", english: "mountain" },
  { japanese: "", hiragana: "やる", english: "to do" },
  { japanese: "夕方", hiragana: "ゆうがた", english: "evening" },
  { japanese: "夕飯", hiragana: "ゆうはん", english: "dinner" },
  { japanese: "郵便局", hiragana: "ゆうびんきょく", english: "post office" },
  { japanese: "昨夜", hiragana: "ゆうべ", english: "last night" },
  { japanese: "有名", hiragana: "ゆうめい", english: "famous" },
  { japanese: "雪", hiragana: "ゆき", english: "snow" },
  { japanese: "行く", hiragana: "ゆく", english: "to go" },
  { japanese: "", hiragana: "ゆっくりと", english: "slowly" },
  { japanese: "八日", hiragana: "ようか", english: "eight days, eighth day of the month" },
  { japanese: "洋服", hiragana: "ようふく", english: "western-style clothes" },
  { japanese: "", hiragana: "よく", english: "often, well" },
  { japanese: "横", hiragana: "よこ", english: "beside, side, width" },
  { japanese: "四日", hiragana: "よっか", english: "four days, fourth day of the month" },
  { japanese: "四つ", hiragana: "よっつ", english: "four" },
  { japanese: "呼ぶ", hiragana: "よぶ", english: "to call out, to invite" },
  { japanese: "読む", hiragana: "よむ", english: "to read" },
  { japanese: "夜", hiragana: "よる", english: "evening, night" },
  { japanese: "弱い", hiragana: "よわい", english: "weak" },
  { japanese: "来月", hiragana: "らいげつ", english: "next month" },
  { japanese: "来週", hiragana: "らいしゅう", english: "next week" },
  { japanese: "来年", hiragana: "らいねん", english: "next year" },
  { japanese: "", hiragana: "ラジオ", english: "radio" },
  { japanese: "", hiragana: "ラジカセ", english: "radio cassette player" },
  { japanese: "", hiragana: "りっぱ", english: "splendid" },
  { japanese: "留学生", hiragana: "りゅうがくせい", english: "overseas student" },
  { japanese: "両親", hiragana: "りょうしん", english: "both parents" },
  { japanese: "料理", hiragana: "りょうり", english: "cuisine" },
  { japanese: "旅行", hiragana: "りょこう", english: "travel" },
  { japanese: "零", hiragana: "れい", english: "zero" },
  { japanese: "冷蔵庫", hiragana: "れいぞうこ", english: "refrigerator" },
  { japanese: "", hiragana: "レコード", english: "record" },
  { japanese: "", hiragana: "レストラン", english: "restaurant" },
  { japanese: "練習", hiragana: "れんしゅうする", english: "to practice" },
  { japanese: "廊下", hiragana: "ろうか", english: "corridor" },
  { japanese: "六", hiragana: "ろく", english: "six" },
  { japanese: "", hiragana: "ワイシャツ", english: "business shirt" },
  { japanese: "若い", hiragana: "わかい", english: "young" },
  { japanese: "分かる", hiragana: "わかる", english: "to be understood" },
  { japanese: "忘れる", hiragana: "わすれる", english: "to forget" },
  { japanese: "私", hiragana: "わたくし", english: "(humble) I,myself" },
  { japanese: "私", hiragana: "わたし", english: "I,myself" },
  { japanese: "渡す", hiragana: "わたす", english: "to hand over" },
  { japanese: "渡る", hiragana: "わたる", english: "to go across" },
  { japanese: "悪い", hiragana: "わるい", english: "bad" }
];

// Fonction pour extraire les mots de la base de données actuelle
const currentWords = vocabularyData.map(word => ({
  japanese: word.japanese,
  hiragana: word.hiragana,
  english: word.english
}));

console.log(`PDF contient: ${pdfWords.length} mots`);
console.log(`Base de données actuelle contient: ${currentWords.length} mots`);

// Trouver les mots manquants
const missingWords = pdfWords.filter(pdfWord => {
  return !currentWords.some(currentWord => 
    currentWord.japanese === pdfWord.japanese && 
    currentWord.hiragana === pdfWord.hiragana
  );
});

console.log(`Mots manquants: ${missingWords.length}`);
console.log('Liste des mots manquants:');
missingWords.forEach(word => {
  console.log(`${word.japanese} (${word.hiragana}) - ${word.english}`);
});

export { missingWords };